baseURL = 'https://fitz.dk'
languageCode = 'en-US'
title = 'Mainframes & More'
enableEmoji = true


[params]
  dateFormat = "02 Jan 2006"
  [params.author]
    email = 'blog@fitz.dk'
    name = 'Jack Fitzsimons'
    copyright = '© 2025 Jack Fitzsimons'


[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menus.main]]
    name = 'Talks'
    pageRef = '/talks'
    weight = 30

[outputs]
  home = ['html']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[services]
  [services.rss]
    limit = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
  [[module.imports]]
    path = "github.com/fitzsimonsjl/vanilje"
